//! Global hotkeys, and the honest account of where they do not exist.
//!
//! A hotkey that silently does nothing is the worst failure this class of app
//! has: the user presses the key, no capture appears, and there is nothing on
//! screen to explain why. Everything in this module exists to make that outcome
//! impossible — either the binding works, or the caller gets an error carrying
//! the remedy in words the user can act on.
//!
//! Three things can go wrong, and each is a distinct, reported outcome rather
//! than a silent no-op:
//!
//! 1. **The combination is already Scrozz's.** Caught in [`GlobalHotkeys`]'s own
//!    bookkeeping before the OS is touched.
//! 2. **The combination belongs to the OS.** `Cmd+Shift+4` is macOS's own
//!    screenshot shortcut, and — this is the trap — Carbon's
//!    `RegisterEventHotKey` returns success for it anyway. The system keeps the
//!    key and Scrozz's handler never fires. No API reports this, so
//!    [`reserved_shortcuts`] is a table of the combinations known to be taken,
//!    checked before registering.
//! 3. **The platform has no global hotkeys at all.** See below.
//!
//! # Wayland (decision D11)
//!
//! On wlroots compositors — sway, Hyprland, river — there is **no
//! `GlobalShortcuts` portal**, and a Wayland client cannot grab keys. There is
//! no implementation to write: the only path that exists is the user binding a
//! compositor keybinding to the `scrozz` CLI. That is why the CLI is a platform
//! requirement rather than a convenience.
//!
//! [`register`](HotkeyManager::register) therefore returns
//! [`Error::Unsupported`] there, and its `why` carries the exact config line to
//! paste, generated by [`Compositor::binding_for`]. Onboarding shows it. A user
//! who is not told this concludes the app is broken.
//!
//! GNOME and KDE on Wayland *do* implement the portal, but the `global-hotkey`
//! crate this module builds on is X11-only, and an X11 grab under XWayland does
//! not see native Wayland keystrokes. Rather than register a binding that
//! appears to work and never fires, those sessions also report `Unsupported`,
//! with a `why` that says the portal exists and is not yet wired up.

use std::collections::HashMap;
use std::fmt;

use global_hotkey::hotkey::{Code, HotKey, Modifiers};
use global_hotkey::{GlobalHotKeyEvent, GlobalHotKeyManager, HotKeyState};
use scrozz_core::{Error, Result};

use crate::{Hotkey, HotkeyManager};

// ---------------------------------------------------------------------------
// Accelerators
// ---------------------------------------------------------------------------

/// A parsed, platform-normalised key combination.
///
/// Accelerators are written platform-independently — `"Cmd+Shift+4"` — and
/// normalised on parse. `Cmd`, `Command`, `Super` and `Meta` are interchangeable
/// spellings of the *primary* modifier, which is Command on macOS and **Control
/// on Windows and Linux**, because `Super` on those platforms is the desktop
/// environment's key and binding it fights the window manager.
///
/// The physical Super/Windows key is still reachable, spelled `Win` or `Logo`,
/// for the rare binding that genuinely wants it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Accelerator {
    mods: Modifiers,
    code: Code,
}

impl Accelerator {
    /// Parses a platform-independent accelerator string.
    ///
    /// Modifiers may appear in any order and the key may appear anywhere, so
    /// long as there is exactly one non-modifier token. Matching is
    /// case-insensitive and whitespace around `+` is ignored.
    ///
    /// # Errors
    ///
    /// Returns [`Error::InvalidRequest`] if a token is empty, unrecognised, or
    /// if the string does not name exactly one non-modifier key.
    pub fn parse(input: &str) -> Result<Self> {
        let mut mods = Modifiers::empty();
        let mut code: Option<Code> = None;

        for raw in input.split('+') {
            let token = raw.trim();
            if token.is_empty() {
                return Err(Error::InvalidRequest(format!(
                    "hotkey \"{input}\" has an empty component; write it as \
                     Modifier+Modifier+Key, e.g. \"Cmd+Shift+4\""
                )));
            }

            if let Some(modifier) = parse_modifier(token) {
                mods |= modifier;
                continue;
            }

            let parsed = parse_code(token).ok_or_else(|| {
                Error::InvalidRequest(format!(
                    "hotkey \"{input}\" names an unrecognised key \"{token}\""
                ))
            })?;

            if code.replace(parsed).is_some() {
                return Err(Error::InvalidRequest(format!(
                    "hotkey \"{input}\" names more than one non-modifier key; \
                     exactly one is required"
                )));
            }
        }

        let code = code.ok_or_else(|| {
            Error::InvalidRequest(format!(
                "hotkey \"{input}\" is only modifiers; it must also name a key, \
                 e.g. \"Cmd+Shift+4\""
            ))
        })?;

        Ok(Self { mods, code })
    }

    /// The keysym name a Wayland compositor's config file expects.
    ///
    /// `None` for keys with no stable X11 keysym spelling, which is the signal
    /// that no config line can be generated for this combination.
    #[must_use]
    pub fn keysym(&self) -> Option<&'static str> {
        keysym_for(self.code)
    }

    /// Whether this is a combination the OS itself has already taken.
    ///
    /// See [`reserved_shortcuts`] for why this cannot be left to the platform.
    #[must_use]
    pub fn system_owner(&self) -> Option<&'static ReservedShortcut> {
        reserved_shortcuts()
            .iter()
            .find(|reserved| Self::parse(reserved.accelerator).is_ok_and(|it| it == *self))
    }

    /// Whether the physical Control modifier is present.
    #[must_use]
    pub const fn has_control(self) -> bool {
        self.mods.contains(Modifiers::CONTROL)
    }

    /// Whether the physical Alt/Option modifier is present.
    #[must_use]
    pub const fn has_alt(self) -> bool {
        self.mods.contains(Modifiers::ALT)
    }

    /// Whether the Shift modifier is present.
    #[must_use]
    pub const fn has_shift(self) -> bool {
        self.mods.contains(Modifiers::SHIFT)
    }

    /// Whether the physical Command/Super modifier is present.
    #[must_use]
    pub const fn has_super(self) -> bool {
        self.mods.contains(Modifiers::SUPER)
    }

    /// The canonical display spelling of the non-modifier key.
    #[must_use]
    pub fn key_name(self) -> String {
        display_for(self.code)
    }

    fn to_hotkey(self) -> HotKey {
        HotKey::new(Some(self.mods), self.code)
    }

    fn id(self) -> u32 {
        self.to_hotkey().id()
    }
}

impl fmt::Display for Accelerator {
    /// Renders in the platform's own idiom: `Ctrl+Alt+Shift+Cmd+Key` order on
    /// macOS, which is the order Apple prints them in, and the same order with
    /// `Win` in place of `Cmd` elsewhere.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.mods.contains(Modifiers::CONTROL) {
            write!(f, "Ctrl+")?;
        }
        if self.mods.contains(Modifiers::ALT) {
            write!(
                f,
                "{}+",
                if cfg!(target_os = "macos") {
                    "Opt"
                } else {
                    "Alt"
                }
            )?;
        }
        if self.mods.contains(Modifiers::SHIFT) {
            write!(f, "Shift+")?;
        }
        if self.mods.contains(Modifiers::SUPER) {
            write!(
                f,
                "{}+",
                if cfg!(target_os = "macos") {
                    "Cmd"
                } else {
                    "Win"
                }
            )?;
        }
        write!(f, "{}", display_for(self.code))
    }
}

/// The modifier that `Cmd`, `Command`, `Super` and `Meta` all name here.
const PRIMARY: Modifiers = if cfg!(target_os = "macos") {
    Modifiers::SUPER
} else {
    Modifiers::CONTROL
};

fn parse_modifier(token: &str) -> Option<Modifiers> {
    match token.to_ascii_uppercase().as_str() {
        // Interchangeable spellings of the primary modifier. `Cmd` maps to
        // Control off macOS, which is what a cross-platform default means.
        "CMD" | "COMMAND" | "SUPER" | "META" | "CMDORCTRL" | "CMDORCONTROL" | "COMMANDORCTRL"
        | "COMMANDORCONTROL" => Some(PRIMARY),
        "CTRL" | "CONTROL" => Some(Modifiers::CONTROL),
        "ALT" | "OPT" | "OPTION" => Some(Modifiers::ALT),
        "SHIFT" => Some(Modifiers::SHIFT),
        // The escape hatch: the physical Super/Windows key, unmapped.
        "WIN" | "WINDOWS" | "LOGO" | "HYPER" => Some(Modifiers::SUPER),
        _ => None,
    }
}

/// The key table: parse spelling, display spelling, X11 keysym spelling.
///
/// One table rather than three keeps them from drifting apart, which matters
/// because the keysym column ends up pasted into a user's compositor config.
const KEYS: &[(Code, &str, &str)] = &[
    (Code::Digit0, "0", "0"),
    (Code::Digit1, "1", "1"),
    (Code::Digit2, "2", "2"),
    (Code::Digit3, "3", "3"),
    (Code::Digit4, "4", "4"),
    (Code::Digit5, "5", "5"),
    (Code::Digit6, "6", "6"),
    (Code::Digit7, "7", "7"),
    (Code::Digit8, "8", "8"),
    (Code::Digit9, "9", "9"),
    (Code::KeyA, "A", "a"),
    (Code::KeyB, "B", "b"),
    (Code::KeyC, "C", "c"),
    (Code::KeyD, "D", "d"),
    (Code::KeyE, "E", "e"),
    (Code::KeyF, "F", "f"),
    (Code::KeyG, "G", "g"),
    (Code::KeyH, "H", "h"),
    (Code::KeyI, "I", "i"),
    (Code::KeyJ, "J", "j"),
    (Code::KeyK, "K", "k"),
    (Code::KeyL, "L", "l"),
    (Code::KeyM, "M", "m"),
    (Code::KeyN, "N", "n"),
    (Code::KeyO, "O", "o"),
    (Code::KeyP, "P", "p"),
    (Code::KeyQ, "Q", "q"),
    (Code::KeyR, "R", "r"),
    (Code::KeyS, "S", "s"),
    (Code::KeyT, "T", "t"),
    (Code::KeyU, "U", "u"),
    (Code::KeyV, "V", "v"),
    (Code::KeyW, "W", "w"),
    (Code::KeyX, "X", "x"),
    (Code::KeyY, "Y", "y"),
    (Code::KeyZ, "Z", "z"),
    (Code::F1, "F1", "F1"),
    (Code::F2, "F2", "F2"),
    (Code::F3, "F3", "F3"),
    (Code::F4, "F4", "F4"),
    (Code::F5, "F5", "F5"),
    (Code::F6, "F6", "F6"),
    (Code::F7, "F7", "F7"),
    (Code::F8, "F8", "F8"),
    (Code::F9, "F9", "F9"),
    (Code::F10, "F10", "F10"),
    (Code::F11, "F11", "F11"),
    (Code::F12, "F12", "F12"),
    (Code::F13, "F13", "F13"),
    (Code::F14, "F14", "F14"),
    (Code::F15, "F15", "F15"),
    (Code::F16, "F16", "F16"),
    (Code::F17, "F17", "F17"),
    (Code::F18, "F18", "F18"),
    (Code::F19, "F19", "F19"),
    (Code::F20, "F20", "F20"),
    (Code::Space, "Space", "space"),
    (Code::Enter, "Enter", "Return"),
    (Code::Tab, "Tab", "Tab"),
    (Code::Escape, "Esc", "Escape"),
    (Code::Backspace, "Backspace", "BackSpace"),
    (Code::Delete, "Delete", "Delete"),
    (Code::Insert, "Insert", "Insert"),
    (Code::Home, "Home", "Home"),
    (Code::End, "End", "End"),
    (Code::PageUp, "PageUp", "Prior"),
    (Code::PageDown, "PageDown", "Next"),
    (Code::PrintScreen, "PrintScreen", "Print"),
    (Code::ArrowUp, "Up", "Up"),
    (Code::ArrowDown, "Down", "Down"),
    (Code::ArrowLeft, "Left", "Left"),
    (Code::ArrowRight, "Right", "Right"),
    (Code::Comma, ",", "comma"),
    (Code::Period, ".", "period"),
    (Code::Slash, "/", "slash"),
    (Code::Backslash, "\\", "backslash"),
    (Code::Semicolon, ";", "semicolon"),
    (Code::Quote, "'", "apostrophe"),
    (Code::BracketLeft, "[", "bracketleft"),
    (Code::BracketRight, "]", "bracketright"),
    (Code::Backquote, "`", "grave"),
    (Code::Minus, "-", "minus"),
    (Code::Equal, "=", "equal"),
];

fn parse_code(token: &str) -> Option<Code> {
    let upper = token.to_ascii_uppercase();
    KEYS.iter()
        .find(|(code, display, _)| {
            display.eq_ignore_ascii_case(token)
                // Accept the DOM spellings too, so a config file written as
                // `Digit4` or `KeyA` round-trips.
                || format!("{code}").eq_ignore_ascii_case(&upper)
        })
        .map(|(code, _, _)| *code)
}

fn display_for(code: Code) -> String {
    KEYS.iter()
        .find(|(candidate, _, _)| *candidate == code)
        .map_or_else(
            || format!("{code}"),
            |(_, display, _)| (*display).to_owned(),
        )
}

fn keysym_for(code: Code) -> Option<&'static str> {
    KEYS.iter()
        .find(|(candidate, _, _)| *candidate == code)
        .map(|(_, _, keysym)| *keysym)
}

// ---------------------------------------------------------------------------
// Conflicts
// ---------------------------------------------------------------------------

/// A key combination the operating system has already claimed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReservedShortcut {
    /// The combination, in Scrozz's platform-independent spelling.
    pub accelerator: &'static str,
    /// What owns it, in the user's words — "macOS Screenshot", "Spotlight".
    pub owner: &'static str,
    /// Where the user would go to free it up, if they want to.
    pub remedy: &'static str,
}

/// Combinations this platform has already taken.
///
/// This table exists because **no platform API will tell you**. On macOS,
/// `RegisterEventHotKey` returns `noErr` for `Cmd+Shift+4` and then the system
/// keeps the key; on Windows `RegisterHotKey` does fail for most reserved
/// combinations but not for shell-owned ones. Registering into a conflict and
/// waiting to find out is exactly the silent failure this module exists to
/// prevent, so the check happens first, from a table.
///
/// It is deliberately short: only combinations that are reserved by default on
/// a stock system, where being wrong would be worse than being silent.
#[must_use]
pub const fn reserved_shortcuts() -> &'static [ReservedShortcut] {
    #[cfg(target_os = "macos")]
    {
        const SETTINGS: &str =
            "System Settings › Keyboard › Keyboard Shortcuts, or pick another combination";
        &[
            ReservedShortcut {
                accelerator: "Cmd+Shift+3",
                owner: "macOS Screenshot (whole screen)",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Cmd+Shift+4",
                owner: "macOS Screenshot (selection)",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Cmd+Shift+5",
                owner: "macOS Screenshot (capture options)",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Cmd+Shift+6",
                owner: "macOS Screenshot (Touch Bar)",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Cmd+Space",
                owner: "Spotlight",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Ctrl+Space",
                owner: "the input source switcher",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Cmd+Tab",
                owner: "the application switcher",
                remedy: "reserved by macOS and cannot be reassigned",
            },
            ReservedShortcut {
                accelerator: "Cmd+Opt+Esc",
                owner: "Force Quit",
                remedy: "reserved by macOS and cannot be reassigned",
            },
        ]
    }

    #[cfg(target_os = "windows")]
    {
        const SETTINGS: &str = "reserved by Windows; pick another combination";
        &[
            ReservedShortcut {
                accelerator: "Win+Shift+S",
                owner: "Snipping Tool",
                remedy: "Settings › Accessibility › Keyboard, or pick another combination",
            },
            ReservedShortcut {
                accelerator: "Win+PrintScreen",
                owner: "the Windows screenshot shortcut",
                remedy: "Settings › Accessibility › Keyboard, or pick another combination",
            },
            ReservedShortcut {
                accelerator: "Win+L",
                owner: "Lock",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Win+D",
                owner: "Show desktop",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Win+Tab",
                owner: "Task View",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Alt+Tab",
                owner: "the window switcher",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Ctrl+Alt+Delete",
                owner: "the secure attention sequence",
                remedy: "reserved by Windows and cannot be reassigned",
            },
        ]
    }

    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    {
        const SETTINGS: &str = "your desktop's keyboard settings, or pick another combination";
        &[
            ReservedShortcut {
                accelerator: "PrintScreen",
                owner: "the desktop screenshot tool",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Shift+PrintScreen",
                owner: "the desktop screenshot tool (selection)",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Alt+PrintScreen",
                owner: "the desktop screenshot tool (window)",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Alt+Tab",
                owner: "the window switcher",
                remedy: SETTINGS,
            },
            ReservedShortcut {
                accelerator: "Ctrl+Alt+Delete",
                owner: "the session manager",
                remedy: SETTINGS,
            },
        ]
    }
}

/// Why a hotkey could not be bound, in a form a settings pane can render.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Conflict {
    /// Scrozz already binds this combination to another action.
    AlreadyBound {
        /// The action currently holding it.
        action: String,
    },
    /// The operating system holds this combination.
    SystemReserved {
        /// What holds it, and where the user would free it.
        reserved: ReservedShortcut,
    },
    /// The OS refused at registration time, for a reason it did not elaborate.
    Refused {
        /// The platform's own words.
        detail: String,
    },
}

impl fmt::Display for Conflict {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::AlreadyBound { action } => {
                write!(f, "already bound in Scrozz to \"{action}\"")
            }
            Self::SystemReserved { reserved } => write!(
                f,
                "already used by {}; free it in {}",
                reserved.owner, reserved.remedy
            ),
            Self::Refused { detail } => write!(f, "the system refused it: {detail}"),
        }
    }
}

// ---------------------------------------------------------------------------
// Session detection
// ---------------------------------------------------------------------------

/// The windowing system underneath.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DisplayServer {
    /// macOS.
    Quartz,
    /// Windows.
    Windows,
    /// X11, including XWayland used as an X server by an X11 session.
    X11,
    /// A Wayland session.
    Wayland,
    /// Nothing detected — headless, CI, or a bare TTY.
    Headless,
}

/// The Wayland compositor, where one is running.
///
/// The distinction that matters is not cosmetic: the wlroots family implements
/// no `GlobalShortcuts` portal at all, so for those the only hotkey path is a
/// compositor keybinding invoking the CLI.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Compositor {
    /// sway — wlroots, no global shortcut portal.
    Sway,
    /// Hyprland — wlroots, no global shortcut portal.
    Hyprland,
    /// river — wlroots, no global shortcut portal.
    River,
    /// niri — no global shortcut portal.
    Niri,
    /// Wayfire — wlroots, no global shortcut portal.
    Wayfire,
    /// GNOME/Mutter — implements the portal.
    Gnome,
    /// KDE/KWin — implements the portal.
    Kde,
    /// Not a Wayland session, or a compositor Scrozz does not recognise.
    Other,
}

impl Compositor {
    /// Whether this compositor implements the `GlobalShortcuts` portal.
    ///
    /// `false` for the wlroots family. This is the fact D11 is built on.
    #[must_use]
    pub const fn has_global_shortcut_portal(self) -> bool {
        matches!(self, Self::Gnome | Self::Kde)
    }

    /// The config file the user would edit, for display alongside the line.
    #[must_use]
    pub const fn config_path(self) -> Option<&'static str> {
        match self {
            Self::Sway => Some("~/.config/sway/config"),
            Self::Hyprland => Some("~/.config/hypr/hyprland.conf"),
            Self::River => Some("~/.config/river/init"),
            Self::Niri => Some("~/.config/niri/config.kdl"),
            _ => None,
        }
    }

    /// The exact config line binding `accelerator` to `command`.
    ///
    /// This is the whole remedy on wlroots, so it is generated rather than
    /// described: onboarding shows it and the user pastes it. `None` when the
    /// compositor has no known config syntax, or when the key has no keysym
    /// spelling to put in the file.
    #[must_use]
    pub fn binding_for(self, accelerator: &Accelerator, command: &str) -> Option<String> {
        let key = accelerator.keysym()?;
        let mods = accelerator.mods;

        let line = match self {
            Self::Sway => {
                let mut parts = Vec::new();
                if mods.contains(Modifiers::CONTROL) {
                    parts.push("Ctrl");
                }
                if mods.contains(Modifiers::ALT) {
                    parts.push("Mod1");
                }
                if mods.contains(Modifiers::SHIFT) {
                    parts.push("Shift");
                }
                if mods.contains(Modifiers::SUPER) {
                    parts.push("Mod4");
                }
                parts.push(key);
                format!("bindsym {} exec {command}", parts.join("+"))
            }
            Self::Hyprland => {
                let mut parts = Vec::new();
                if mods.contains(Modifiers::CONTROL) {
                    parts.push("CTRL");
                }
                if mods.contains(Modifiers::ALT) {
                    parts.push("ALT");
                }
                if mods.contains(Modifiers::SHIFT) {
                    parts.push("SHIFT");
                }
                if mods.contains(Modifiers::SUPER) {
                    parts.push("SUPER");
                }
                format!("bind = {}, {key}, exec, {command}", parts.join("_"))
            }
            Self::River => {
                let mut parts = Vec::new();
                if mods.contains(Modifiers::CONTROL) {
                    parts.push("Control");
                }
                if mods.contains(Modifiers::ALT) {
                    parts.push("Mod1");
                }
                if mods.contains(Modifiers::SHIFT) {
                    parts.push("Shift");
                }
                if mods.contains(Modifiers::SUPER) {
                    parts.push("Super");
                }
                if parts.is_empty() {
                    parts.push("None");
                }
                format!(
                    "riverctl map normal {} {key} spawn '{command}'",
                    parts.join("+")
                )
            }
            Self::Niri => {
                let mut parts = Vec::new();
                if mods.contains(Modifiers::CONTROL) {
                    parts.push("Ctrl");
                }
                if mods.contains(Modifiers::ALT) {
                    parts.push("Alt");
                }
                if mods.contains(Modifiers::SHIFT) {
                    parts.push("Shift");
                }
                if mods.contains(Modifiers::SUPER) {
                    parts.push("Mod");
                }
                parts.push(key);
                format!("{} {{ spawn-sh \"{command}\"; }}", parts.join("+"))
            }
            Self::Wayfire | Self::Gnome | Self::Kde | Self::Other => return None,
        };

        Some(line)
    }
}

/// What the environment allows, decided once at construction.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Session {
    /// The windowing system.
    pub server: DisplayServer,
    /// The compositor, on Wayland.
    pub compositor: Compositor,
    /// The raw `XDG_CURRENT_DESKTOP`, kept for diagnostics.
    pub desktop: String,
}

impl Session {
    /// Reads the current environment.
    #[must_use]
    pub fn detect() -> Self {
        let desktop = std::env::var("XDG_CURRENT_DESKTOP").unwrap_or_default();

        if cfg!(target_os = "macos") {
            return Self {
                server: DisplayServer::Quartz,
                compositor: Compositor::Other,
                desktop,
            };
        }
        if cfg!(target_os = "windows") {
            return Self {
                server: DisplayServer::Windows,
                compositor: Compositor::Other,
                desktop,
            };
        }

        Self::from_env(
            Some(desktop.as_str()),
            std::env::var("WAYLAND_DISPLAY").ok().as_deref(),
            std::env::var("XDG_SESSION_TYPE").ok().as_deref(),
            std::env::var("DISPLAY").ok().as_deref(),
        )
    }

    /// Classifies a Unix session from explicit environment values.
    ///
    /// Deliberately free of `cfg!(target_os)` and of any read of the real
    /// environment, so every branch — including every Wayland compositor — is
    /// reachable from a test on any platform. A version that read the process
    /// environment could only be tested by mutating it, which no parallel test
    /// suite can do safely.
    #[must_use]
    pub fn from_env(
        xdg_current_desktop: Option<&str>,
        wayland_display: Option<&str>,
        xdg_session_type: Option<&str>,
        x11_display: Option<&str>,
    ) -> Self {
        let desktop = xdg_current_desktop.unwrap_or_default().to_owned();

        let on_wayland = wayland_display.is_some_and(|it| !it.is_empty())
            || xdg_session_type.is_some_and(|it| it.eq_ignore_ascii_case("wayland"));

        // XDG_CURRENT_DESKTOP is colon-separated and may be "sway" or
        // "Hyprland" or "GNOME:GNOME-Classic".
        let compositor = desktop
            .split(':')
            .find_map(|part| match part.trim().to_ascii_lowercase().as_str() {
                "sway" => Some(Compositor::Sway),
                "hyprland" => Some(Compositor::Hyprland),
                "river" => Some(Compositor::River),
                "niri" => Some(Compositor::Niri),
                "wayfire" => Some(Compositor::Wayfire),
                "gnome" | "gnome-classic" | "ubuntu" | "pop" => Some(Compositor::Gnome),
                "kde" | "plasma" => Some(Compositor::Kde),
                _ => None,
            })
            .unwrap_or(Compositor::Other);

        let server = if on_wayland {
            DisplayServer::Wayland
        } else if xdg_session_type.is_some_and(|it| it.eq_ignore_ascii_case("x11"))
            || x11_display.is_some_and(|it| !it.is_empty())
        {
            DisplayServer::X11
        } else {
            DisplayServer::Headless
        };

        Self {
            server,
            compositor,
            desktop,
        }
    }

    /// Whether global hotkeys can be registered at all here.
    #[must_use]
    pub const fn supports_global_hotkeys(&self) -> bool {
        !matches!(self.server, DisplayServer::Wayland)
    }

    /// The `Unsupported` error this session produces, with its remedy.
    ///
    /// Split out and public because onboarding renders exactly this text
    /// (decision D26 item 4) rather than inventing its own wording.
    #[must_use]
    pub fn unsupported(&self, accelerator: &Accelerator, command: &str) -> Error {
        let why = if self.compositor.has_global_shortcut_portal() {
            format!(
                "{desktop} on Wayland implements the GlobalShortcuts portal, but Scrozz does \
                 not speak it yet, and an X11 grab under XWayland never sees Wayland \
                 keystrokes — a binding here would look registered and never fire. Bind \
                 {accelerator} to `{command}` in your desktop's keyboard settings instead.",
                desktop = if self.desktop.is_empty() {
                    "this desktop"
                } else {
                    &self.desktop
                },
            )
        } else if let Some(line) = self.compositor.binding_for(accelerator, command) {
            let path = self
                .compositor
                .config_path()
                .unwrap_or("your compositor config");
            format!(
                "wlroots compositors implement no global shortcut portal, so no application \
                 can register a system-wide hotkey. Bind it in the compositor instead — add \
                 this to {path}:\n\n    {line}\n\nthen reload the config."
            )
        } else {
            format!(
                "this Wayland compositor implements no global shortcut portal, so no \
                 application can register a system-wide hotkey. Bind a compositor keybinding \
                 to `{command}` instead."
            )
        };

        Error::Unsupported {
            what: format!("global hotkey {accelerator}"),
            why,
        }
    }
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

/// Whether the key went down or came up.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyState {
    /// The combination was pressed.
    Pressed,
    /// The combination was released.
    Released,
}

/// A hotkey firing, resolved back to the action it was bound to.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HotkeyEvent {
    /// The action name given to [`HotkeyManager::register`].
    pub action: String,
    /// The combination that fired.
    pub accelerator: Accelerator,
    /// Down or up.
    pub state: KeyState,
}

// ---------------------------------------------------------------------------
// The manager
// ---------------------------------------------------------------------------

struct Binding {
    action: String,
    accelerator: Accelerator,
}

enum Backend {
    /// Bound to the OS.
    Os(Box<GlobalHotKeyManager>),
    /// Bookkeeping only — no OS registration happens.
    ///
    /// Used by the CLI, by headless tests, and on Wayland, where there is
    /// nothing to bind to. Tests use this so a test run can never grab a key
    /// off the machine it runs on.
    Detached,
}

/// Registers system-wide hotkeys, or explains why it cannot.
///
/// # Threading
///
/// [`GlobalHotkeys::new`] must be called on the **main thread**, and a platform
/// event loop must already be running on it: macOS delivers Carbon hotkey events
/// to the main run loop and Windows to the thread's win32 message queue. There
/// is no diagnostic if this is got wrong — the hotkey simply never fires — so
/// treat it as a hard requirement. [`GlobalHotkeys::detached`] has no such
/// constraint.
pub struct GlobalHotkeys {
    backend: Backend,
    session: Session,
    /// The command onboarding tells the user to bind, on platforms where they
    /// must do it themselves.
    command: String,
    bindings: HashMap<Accelerator, Binding>,
    by_id: HashMap<u32, Accelerator>,
}

impl GlobalHotkeys {
    /// Binds to the OS, or falls back to bookkeeping where the OS offers
    /// nothing to bind to.
    ///
    /// On Wayland this succeeds and produces a manager whose
    /// [`register`](HotkeyManager::register) returns [`Error::Unsupported`] with
    /// the remedy — deliberately, because failing at construction would leave
    /// the caller with nothing to show the user.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Platform`] if the platform hotkey subsystem could not be
    /// initialised.
    pub fn new() -> Result<Self> {
        let session = Session::detect();
        let backend = if session.supports_global_hotkeys() {
            Backend::Os(Box::new(GlobalHotKeyManager::new().map_err(|err| {
                Error::Platform(format!("could not start the hotkey listener: {err}"))
            })?))
        } else {
            Backend::Detached
        };

        Ok(Self::with_backend(backend, session))
    }

    /// A manager that never touches the OS.
    ///
    /// Conflict detection, bookkeeping and config-line generation all work; no
    /// key is grabbed. This is what the CLI uses, what headless tests use, and
    /// what makes it possible to test this module without hijacking the
    /// keyboard of the machine running the tests.
    #[must_use]
    pub fn detached() -> Self {
        Self::with_backend(Backend::Detached, Session::detect())
    }

    /// A detached manager for pure conflict validation.
    ///
    /// Unlike [`Self::detached`], this deliberately has no detected display
    /// session. Registering entries seeds only the in-memory conflict table, so
    /// validation remains available on Wayland even though real registration is
    /// unsupported there.
    #[must_use]
    pub fn detached_for_conflict_checks() -> Self {
        Self::with_backend(Backend::Detached, Session::from_env(None, None, None, None))
    }

    /// A detached manager reporting a session it is not actually running in.
    ///
    /// The only way to exercise the Wayland paths from macOS or CI.
    #[must_use]
    pub fn detached_in(session: Session) -> Self {
        Self::with_backend(Backend::Detached, session)
    }

    fn with_backend(backend: Backend, session: Session) -> Self {
        Self {
            backend,
            session,
            command: "scrozz capture region".to_owned(),
            bindings: HashMap::new(),
            by_id: HashMap::new(),
        }
    }

    /// Sets the CLI invocation used in generated compositor config lines.
    pub fn set_command(&mut self, command: impl Into<String>) {
        self.command = command.into();
    }

    /// The detected session.
    #[must_use]
    pub const fn session(&self) -> &Session {
        &self.session
    }

    /// Whether this manager is actually bound to the OS.
    #[must_use]
    pub const fn is_bound_to_os(&self) -> bool {
        matches!(self.backend, Backend::Os(_))
    }

    /// Tests a combination without registering it.
    ///
    /// This is what a settings pane calls as the user types a new shortcut, so
    /// the conflict is shown before they commit to it rather than after.
    ///
    /// # Errors
    ///
    /// Returns [`Error::InvalidRequest`] if the accelerator does not parse.
    pub fn check(&self, hotkey: &Hotkey) -> Result<Option<Conflict>> {
        let accelerator = Accelerator::parse(&hotkey.accelerator)?;
        Ok(self.conflict_for(&accelerator))
    }

    fn conflict_for(&self, accelerator: &Accelerator) -> Option<Conflict> {
        if let Some(existing) = self.bindings.get(accelerator) {
            return Some(Conflict::AlreadyBound {
                action: existing.action.clone(),
            });
        }
        accelerator
            .system_owner()
            .map(|reserved| Conflict::SystemReserved {
                reserved: *reserved,
            })
    }

    /// The action bound to a combination, if any.
    #[must_use]
    pub fn action_for(&self, accelerator: &Accelerator) -> Option<&str> {
        self.bindings.get(accelerator).map(|it| it.action.as_str())
    }

    /// Every current binding, as `(accelerator, action)`.
    pub fn bindings(&self) -> impl Iterator<Item = (&Accelerator, &str)> {
        self.bindings
            .iter()
            .map(|(accelerator, binding)| (accelerator, binding.action.as_str()))
    }

    /// The config lines a user of this compositor must add, for a set of
    /// *intended* bindings.
    ///
    /// Takes the intent rather than reading [`GlobalHotkeys::bindings`] because
    /// on the compositors this exists for there are never any bindings to read:
    /// [`GlobalHotkeys::register`] refuses on Wayland by design, so a version
    /// that walked its own registrations would return an empty block on exactly
    /// the platform that needs it.
    ///
    /// Onboarding shows the whole block at once — a user pasting one line and
    /// discovering the others are missing is the same failure in slow motion.
    #[must_use]
    pub fn compositor_config<'a>(
        &self,
        intended: impl IntoIterator<Item = (&'a Accelerator, &'a str)>,
        command_for: impl Fn(&str) -> String,
    ) -> Vec<String> {
        let mut lines: Vec<String> = intended
            .into_iter()
            .filter_map(|(accelerator, action)| {
                self.session
                    .compositor
                    .binding_for(accelerator, &command_for(action))
            })
            .collect();
        lines.sort();
        lines
    }

    /// Takes one pending event, if there is one. Never blocks.
    ///
    /// Events whose ids are not ours are dropped: the `global-hotkey` channel is
    /// process-global, so a second manager anywhere in the process feeds the
    /// same queue.
    #[must_use]
    pub fn poll(&self) -> Option<HotkeyEvent> {
        while let Ok(raw) = GlobalHotKeyEvent::receiver().try_recv() {
            if let Some(event) = self.resolve(raw) {
                return Some(event);
            }
        }
        None
    }

    /// Delivers every pending event to `handler`.
    ///
    /// Prefer this to [`GlobalHotKeyEvent::set_event_handler`], which is a
    /// process-global `OnceCell`: setting it once silently stops the channel
    /// feeding *every* consumer in the process for the rest of its life.
    pub fn drain(&self, mut handler: impl FnMut(HotkeyEvent)) {
        while let Ok(raw) = GlobalHotKeyEvent::receiver().try_recv() {
            if let Some(event) = self.resolve(raw) {
                handler(event);
            }
        }
    }

    fn resolve(&self, raw: GlobalHotKeyEvent) -> Option<HotkeyEvent> {
        let accelerator = *self.by_id.get(&raw.id)?;
        let binding = self.bindings.get(&accelerator)?;
        Some(HotkeyEvent {
            action: binding.action.clone(),
            accelerator,
            state: match raw.state {
                HotKeyState::Pressed => KeyState::Pressed,
                HotKeyState::Released => KeyState::Released,
            },
        })
    }

    /// Releases every binding.
    ///
    /// Called from `Drop`, and worth calling explicitly before exit: a hotkey
    /// left registered by a crashed process stays grabbed until the session
    /// ends on X11.
    pub fn unregister_all(&mut self) {
        if let Backend::Os(manager) = &self.backend {
            let keys: Vec<HotKey> = self
                .bindings
                .keys()
                .map(|accelerator| accelerator.to_hotkey())
                .collect();
            if let Err(err) = manager.unregister_all(&keys) {
                tracing::warn!(%err, "could not release all hotkeys");
            }
        }
        self.bindings.clear();
        self.by_id.clear();
    }
}

impl Drop for GlobalHotkeys {
    fn drop(&mut self) {
        self.unregister_all();
    }
}

impl HotkeyManager for GlobalHotkeys {
    fn register(&mut self, hotkey: &Hotkey, action: &str) -> Result<()> {
        let accelerator = Accelerator::parse(&hotkey.accelerator)?;

        // Wayland first: there is no point reporting a conflict for a binding
        // that could never have been made in the first place.
        if !self.session.supports_global_hotkeys() {
            return Err(self.session.unsupported(&accelerator, &self.command));
        }

        if let Some(conflict) = self.conflict_for(&accelerator) {
            return Err(Error::InvalidRequest(format!(
                "hotkey {accelerator} cannot be bound to \"{action}\": {conflict}"
            )));
        }

        if let Backend::Os(manager) = &self.backend {
            manager.register(accelerator.to_hotkey()).map_err(|err| {
                Error::InvalidRequest(format!(
                    "hotkey {accelerator} cannot be bound to \"{action}\": {}",
                    Conflict::Refused {
                        detail: err.to_string()
                    }
                ))
            })?;
        }

        self.by_id.insert(accelerator.id(), accelerator);
        self.bindings.insert(
            accelerator,
            Binding {
                action: action.to_owned(),
                accelerator,
            },
        );
        tracing::debug!(hotkey = %accelerator, action, "bound global hotkey");
        Ok(())
    }

    fn unregister(&mut self, hotkey: &Hotkey) -> Result<()> {
        let accelerator = Accelerator::parse(&hotkey.accelerator)?;

        if !self.bindings.contains_key(&accelerator) {
            return Err(Error::InvalidRequest(format!(
                "hotkey {accelerator} is not bound"
            )));
        }

        if let Backend::Os(manager) = &self.backend {
            manager.unregister(accelerator.to_hotkey()).map_err(|err| {
                Error::Platform(format!("could not release {accelerator}: {err}"))
            })?;
        }
        self.bindings.remove(&accelerator);
        self.by_id.remove(&accelerator.id());
        Ok(())
    }
}
