[package]
name = "scrozz-capture"
description = "Still capture backends for macOS, Windows, X11 and Wayland."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
scrozz-core.workspace = true
thiserror.workspace = true
tracing.workspace = true


[lints]
workspace = true
